apiVersion: apps/v1
kind: Deployment
metadata:
  name: imagemaker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: imagemaker
  template:
    metadata:
      labels:
        app: imagemaker
    spec:
      containers:
      - name: imagectn
        image: sod723/imagemaker:0.1